M48
; DRILL file {KiCad (6.0.5-0)} date Friday, May 20, 2022 at 06:14:07 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-20T18:14:07-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1969
%
G90
G05
T1
X5.7199Y-1.4961
X6.1699Y-1.4961
T2
X1.9291Y-1.4961
X4.252Y-3.8189
X6.5748Y-1.4961
T0
M30
